version: "2.22"

services:
  web:
    build: 
      context: .
    container_name: shichi_web
    command: gunicorn Shichi.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - app_media:/usr/src/app/media/
      - static:/static
    ports:
      - 8000:8000
    env_file:
      - ./Shichi/Shichi/.deploy.env
    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: shichi_db
    volumes:
      - db:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=shichidb
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static:/static
      - app_media:/usr/src/app/media/

volumes:
  db:
  app_media:
  static: