# Generated by Django 4.2.6 on 2023-11-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=50, unique=True)),
                ('money', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('bank_code', models.CharField(max_length=50)),
                ('is_added', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
