# Generated by Django 4.2.6 on 2023-11-16 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentlog',
            name='was_successful',
            field=models.BooleanField(default=False),
        ),
    ]
