# Generated by Django 4.2.6 on 2023-11-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0002_paymentlog_was_successful'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentlog',
            name='user_email',
            field=models.CharField(max_length=50),
        ),
    ]
