# Generated by Django 4.2.6 on 2023-12-29 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='history',
        ),
    ]
