# Generated by Django 4.2.6 on 2023-12-27 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomCarImage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customcarimage',
            name='index',
        ),
    ]
