# Generated by Django 4.2.6 on 2023-12-14 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomDate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdate',
            name='adv_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
