# Generated by Django 4.2.6 on 2023-12-23 13:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CustomDate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomAdvertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('car_name', models.CharField(blank=True, max_length=30)),
                ('car_color', models.CharField(choices=[('black', 'black'), ('white', 'white'), ('gray', 'gray'), ('brown', 'brown'), ('navy-blue', 'navy-blue'), ('others', 'others')], default='others', max_length=20)),
                ('car_produced_date', models.DateField()),
                ('car_seat_count', models.IntegerField(blank=True, null=True)),
                ('car_door_count', models.IntegerField(blank=True, null=True)),
                ('car_Is_cooler', models.BooleanField(default=False)),
                ('car_gearbox', models.CharField(choices=[('manual', 'manual'), ('automatic', 'automatic')], default='manual', max_length=20)),
                ('car_fuel', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('car_category', models.CharField(choices=[('economy', 'economy'), ('luxury', 'luxury'), ('compact', 'compact'), ('offroad', 'offroad'), ('hybrid', 'hybrid'), ('electric', 'electric'), ('truck', 'truck'), ('convertible', 'convertible'), ('passenger-van', 'passenger-van'), ('mini-van', 'mini-van'), ('others', 'others')], default='others', max_length=20)),
                ('location_state', models.CharField(choices=[('Tehran', 'Tehran'), ('Khorasan-Razavi', 'Khorasan-Razavi'), ('Isfahan', 'Isfahan'), ('Fars', 'Fars'), ('Khuzestan', 'Khuzestan'), ('Azarbaijan, East', 'Azarbaijan, East'), ('Azarbaijan, West', 'Azarbaijan, West'), ('Mazandaran', 'Mazandaran'), ('Kerman', 'Kerman'), ('Alborz', 'Alborz'), ('Gilan', 'Gilan'), ('Sistan-and-Baluchestan', 'Sistan-and-Baluchestan'), ('Kermanshah', 'Kermanshah'), ('Hamedan', 'Hamedan'), ('Lorestan', 'Lorestan'), ('Golestan', 'Golestan'), ('Kurdistan', 'Kurdistan'), ('Hormozgan', 'Hormozgan'), ('Markazi', 'Markazi'), ('Ardabil', 'Ardabil'), ('Qazvin', 'Qazvin'), ('Qom', 'Qom'), ('Bushehr', 'Bushehr'), ('Yazd', 'Yazd'), ('Zanjan', 'Zanjan'), ('Chahar-Mahaal-and-Bakhtiari', 'Chahar-Mahaal-and-Bakhtiari'), ('Khorasan-North', 'Khorasan-North'), ('Khorasan-South', 'Khorasan-South'), ('Kohgiluyeh-and-Boyer-Ahmad', 'Kohgiluyeh-and-Boyer-Ahmad'), ('Semnan', 'Semnan'), ('Ilam', 'Ilam')], default='Tehran', max_length=30)),
                ('location_geo_width', models.CharField(blank=True, max_length=30)),
                ('location_geo_length', models.CharField(blank=True, max_length=30)),
                ('available_date_list', models.ManyToManyField(to='CustomDate.customdate')),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('rate', models.DecimalField(decimal_places=1, default=0, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('adv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='CustomAdvertisement.customadvertisement')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('text', models.TextField()),
                ('adv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='CustomAdvertisement.customadvertisement')),
            ],
        ),
    ]
