# Generated by Django 4.2.6 on 2023-10-16 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CustomCarImage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomAdvertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.IntegerField()),
                ('title', models.CharField(blank=True, max_length=30)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('car_name', models.CharField(blank=True, max_length=30)),
                ('car_color', models.CharField(blank=True, max_length=30)),
                ('car_producted_date', models.DateField()),
                ('car_category', models.CharField(choices=[('economy', 'economy'), ('luxury', 'luxury'), ('compact', 'compact'), ('offroad', 'offroad'), ('hybrid', 'hybrid'), ('electric', 'electic'), ('truck', 'truck'), ('convertible', 'convertible'), ('passenger-van', 'passenger-van'), ('mini-van', 'mini-van'), ('others', 'others')], default='others', max_length=20)),
                ('car_images', models.ManyToManyField(to='CustomCarImage.customcarimage')),
            ],
        ),
    ]
