# Generated by Django 4.2.6 on 2023-10-30 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomAdvertisement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customadvertisement',
            name='car_category',
            field=models.CharField(choices=[('economy', 'economy'), ('luxury', 'luxury'), ('compact', 'compact'), ('offroad', 'offroad'), ('hybrid', 'hybrid'), ('electric', 'electric'), ('truck', 'truck'), ('convertible', 'convertible'), ('passenger-van', 'passenger-van'), ('mini-van', 'mini-van'), ('others', 'others')], default='others', max_length=20),
        ),
    ]
