# Generated by Django 4.2.6 on 2024-01-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomAdvertisement', '0002_remove_customadvertisement_car_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customadvertisement',
            name='car_Is_cooler',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='yes', max_length=3),
        ),
    ]
