# Generated by Django 4.2.6 on 2023-11-01 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CustomAdvertisement', '0002_alter_customadvertisement_car_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('text', models.TextField()),
                ('adv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='CustomAdvertisement.customadvertisement')),
            ],
        ),
    ]
