# Generated by Django 4.2.6 on 2023-11-02 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomAdvertisement', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='user_id',
        ),
    ]
