# Generated by Django 4.2.6 on 2023-11-02 13:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CustomAdvertisement', '0004_rename_user_comment_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('rate', models.DecimalField(decimal_places=1, default=0, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('adv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='CustomAdvertisement.customadvertisement')),
            ],
        ),
    ]
