# Generated by Django 4.2.6 on 2023-11-06 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomAdvertisement', '0005_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customadvertisement',
            old_name='car_producted_date',
            new_name='car_produced_date',
        ),
        migrations.RemoveField(
            model_name='customadvertisement',
            name='title',
        ),
        migrations.AddField(
            model_name='customadvertisement',
            name='car_Is_cooler',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customadvertisement',
            name='car_door_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customadvertisement',
            name='car_fuel',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='customadvertisement',
            name='car_gearbox',
            field=models.CharField(choices=[('manual', 'manual'), ('automatic', 'automatic')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='customadvertisement',
            name='car_seat_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
