# Generated by Django 4.2.6 on 2023-11-06 16:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CustomAdvertisement', '0006_rename_car_producted_date_customadvertisement_car_produced_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customadvertisement',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
