# Generated by Django 4.2.6 on 2023-11-09 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomAdvertisement', '0007_customadvertisement_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customadvertisement',
            name='created_date',
        ),
    ]
