# Generated by Django 4.2.6 on 2023-11-10 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomAdvertisement', '0008_remove_customadvertisement_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customadvertisement',
            name='car_color',
            field=models.CharField(choices=[('black', 'black'), ('white', 'white'), ('gray', 'gray'), ('brown', 'brown'), ('navy-blue', 'navy-blue'), ('others', 'others')], default='others', max_length=20),
        ),
    ]
