# Generated by Django 4.2.6 on 2023-11-16 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomAdvertisement', '0009_alter_customadvertisement_car_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customadvertisement',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='customadvertisement',
            name='start_date',
            field=models.DateField(),
        ),
    ]
