# Generated by Django 4.2.6 on 2023-11-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomAdvertisement', '0010_alter_customadvertisement_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customadvertisement',
            name='car_image2',
            field=models.ImageField(blank=True, upload_to='car_images2/'),
        ),
    ]
