# Generated by Django 4.2.6 on 2023-11-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomAdvertisement', '0011_customadvertisement_car_image2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customadvertisement',
            name='car_image2',
        ),
        migrations.AddField(
            model_name='customadvertisement',
            name='location_geo_length',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='customadvertisement',
            name='location_geo_width',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='customadvertisement',
            name='location_state',
            field=models.CharField(choices=[('Tehran', 'Tehran'), ('Khorasan-Razavi', 'Khorasan-Razavi'), ('Isfahan', 'Isfahan'), ('Fars', 'Fars'), ('Khuzestan', 'Khuzestan'), ('Azarbaijan, East', 'Azarbaijan, East'), ('Azarbaijan, West', 'Azarbaijan, West'), ('Mazandaran', 'Mazandaran'), ('Kerman', 'Kerman'), ('Alborz', 'Alborz'), ('Gilan', 'Gilan'), ('Sistan-and-Baluchestan', 'Sistan-and-Baluchestan'), ('Kermanshah', 'Kermanshah'), ('Hamedan', 'Hamedan'), ('Lorestan', 'Lorestan'), ('Golestan', 'Golestan'), ('Kurdistan', 'Kurdistan'), ('Hormozgan', 'Hormozgan'), ('Markazi', 'Markazi'), ('Ardabil', 'Ardabil'), ('Qazvin', 'Qazvin'), ('Qom', 'Qom'), ('Bushehr', 'Bushehr'), ('Yazd', 'Yazd'), ('Zanjan', 'Zanjan'), ('Chahar-Mahaal-and-Bakhtiari', 'Chahar-Mahaal-and-Bakhtiari'), ('Khorasan-North', 'Khorasan-North'), ('Khorasan-South', 'Khorasan-South'), ('Kohgiluyeh-and-Boyer-Ahmad', 'Kohgiluyeh-and-Boyer-Ahmad'), ('Semnan', 'Semnan'), ('Ilam', 'Ilam')], default='Tehran', max_length=30),
        ),
    ]
