# Generated by Django 4.2.6 on 2023-12-13 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomDate', '__first__'),
        ('CustomAdvertisement', '0012_remove_customadvertisement_car_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customadvertisement',
            name='available_date_list',
            field=models.ManyToManyField(null=True, to='CustomDate.customdate'),
        ),
    ]
