# Generated by Django 4.2.6 on 2023-12-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomDate', '__first__'),
        ('CustomAdvertisement', '0013_customadvertisement_available_date_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customadvertisement',
            name='available_date_list',
            field=models.ManyToManyField(to='CustomDate.customdate'),
        ),
    ]
