# Generated by Django 4.2.6 on 2023-10-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomAdvertisementLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=30)),
                ('state', models.CharField(blank=True, max_length=30)),
                ('geo_width', models.CharField(blank=True, max_length=30)),
                ('geo_length', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
