# Generated by Django 4.2.6 on 2023-10-16 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CustomAdvertisement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomHistories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CustomAdvertisement.customadvertisement')),
            ],
        ),
    ]
