# Generated by Django 4.2.6 on 2023-10-16 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CustomAdvertisement', '0001_initial'),
        ('CustomHistories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customhistories',
            name='advertisement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='CustomAdvertisement.customadvertisement'),
        ),
    ]
