# Generated by Django 4.2.6 on 2023-11-09 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomHistories', '0002_alter_customhistories_advertisement'),
    ]

    operations = [
        migrations.AddField(
            model_name='customhistories',
            name='take_or_own',
            field=models.CharField(default='take'),
        ),
    ]
